service: like-button-serverless
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 128

functions:
  likePost:
    handler: likePost.handle
  getPost:
    handler: getPost.handle
