service: like-button
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  memorySize: 256
  tracing:
    lambda: true
  environment:
    FAUNADB_SECRET: fnAD239djvACE7wQsdil8bdy4vrcggodfreNldCh
    ORIGIN_ADDRESS: http://18.231.192.14

functions:
  likePost:
    handler: likePost.handle
    events:
      - http:
          path: likepost/{id}
          method: get
          cors:
            headers:
              - Content-Type
            allowCredentials: false
  getPost:
    handler: getPost.handle
    events:
      - http:
          path: getpost/{id}
          method: get
          cors:
            headers:
              - Content-Type
            allowCredentials: false